### ISSUE TITLE
inconsistent readme

### ISSUE THREAD

**Issue by rawgni** [ernestio/ernest-cli#50]
The `Set up` and `Run it` instruction seems to be incorrect.
It should be `ernest-cli` instead of `ernest` based on the `Installation` instruction.

`make` and `make-install` will create `ernest-cli`.
`make-build`, however will create `ernest`.

Depending on which one to use, the doc on the main site probably has to be changed accordingly.

**Comment by adriacidre** [comment]
Sorry @rawgni completely missed that one, I've moved it to the central issue repo, so it can be fixed asap :-)
